services:
  backend:
    build:
      context: .
      target: development
    container_name: consulting-gpt-backend
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=consulting_gpt
      - DATABASE_URL=postgresql://postgres:postgres@db/consulting_gpt
      - PYTHONUNBUFFERED=1
      - SELENIUM_URL=http://chrome:4444/wd/hub
    depends_on:
      - db
      - chrome
    networks:
      - consulting-gpt-network

  chrome:
    image: seleniarm/standalone-chromium:latest  # Changed to ARM-compatible image
    container_name: chrome
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: "2g"
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    networks:
      - consulting-gpt-network

  db:
    image: postgres:15
    container_name: consulting-gpt-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=consulting_gpt
    ports:
      - '5432:5432'
    networks:
      - consulting-gpt-network

volumes:
  postgres_data:

networks:
  consulting-gpt-network:
    driver: bridge