"""Add source field to guidelines table

Revision ID: add_source_to_guidelines
Revises: 4bc3a1c90a04
Create Date: 2025-07-20 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_source_to_guidelines'
down_revision: Union[str, None] = '4bc3a1c90a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add source column to guidelines table
    op.add_column('guidelines', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove source column from guidelines table
    op.drop_column('guidelines', 'source')
    # ### end Alembic commands ###
