"""Initial migration

Revision ID: 849349273c64
Revises: 
Create Date: 2025-05-20 22:29:06.580601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849349273c64'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=True),
    sa.Column('search_keywords', sa.Text(), nullable=True),
    sa.Column('num_of_axes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_id'), 'technology', ['id'], unique=False)
    op.create_index(op.f('ix_technology_name'), 'technology', ['name'], unique=True)
    op.create_table('comparison_axis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('axis_name', sa.String(length=255), nullable=True),
    sa.Column('extreme1', sa.String(length=255), nullable=True),
    sa.Column('extreme2', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_axis_id'), 'comparison_axis', ['id'], unique=False)
    op.create_table('patent_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('search_query', sa.String(length=512), nullable=True),
    sa.Column('search_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_search_id'), 'patent_search', ['id'], unique=False)
    op.create_table('pca_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('transformed_data', sa.JSON(), nullable=True),
    sa.Column('total_variance_explained', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pca_results_id'), 'pca_results', ['id'], unique=False)
    op.create_table('related_paper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('paper_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.String(length=512), nullable=True),
    sa.Column('publication_date', sa.String(length=255), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('col', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_paper_id'), 'related_paper', ['id'], unique=False)
    op.create_table('related_technology',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('document_id', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('publication_date', sa.String(length=255), nullable=True),
    sa.Column('inventors', sa.JSON(), nullable=True),
    sa.Column('assignees', sa.JSON(), nullable=True),
    sa.Column('col', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_related_technology_id'), 'related_technology', ['id'], unique=False)
    op.create_table('market_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=True),
    sa.Column('related_technology_id', sa.Integer(), nullable=True),
    sa.Column('axis_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['axis_id'], ['comparison_axis.id'], ),
    sa.ForeignKeyConstraint(['related_technology_id'], ['related_technology.id'], ),
    sa.ForeignKeyConstraint(['technology_id'], ['technology.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_analysis_id'), 'market_analysis', ['id'], unique=False)
    op.create_table('patent_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=True),
    sa.Column('patent_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['patent_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_result_id'), 'patent_result', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patent_result_id'), table_name='patent_result')
    op.drop_table('patent_result')
    op.drop_index(op.f('ix_market_analysis_id'), table_name='market_analysis')
    op.drop_table('market_analysis')
    op.drop_index(op.f('ix_related_technology_id'), table_name='related_technology')
    op.drop_table('related_technology')
    op.drop_index(op.f('ix_related_paper_id'), table_name='related_paper')
    op.drop_table('related_paper')
    op.drop_index(op.f('ix_pca_results_id'), table_name='pca_results')
    op.drop_table('pca_results')
    op.drop_index(op.f('ix_patent_search_id'), table_name='patent_search')
    op.drop_table('patent_search')
    op.drop_index(op.f('ix_comparison_axis_id'), table_name='comparison_axis')
    op.drop_table('comparison_axis')
    op.drop_index(op.f('ix_technology_name'), table_name='technology')
    op.drop_index(op.f('ix_technology_id'), table_name='technology')
    op.drop_table('technology')
    # ### end Alembic commands ###
